//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsgereMektub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esgeremektubEntities : DbContext
    {
        public esgeremektubEntities()
            : base("name=esgeremektubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<FightMemory> FightMemory { get; set; }
        public virtual DbSet<Letters> Letters { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<FMtext> FMtext { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
    }
}
