//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsgereMektub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letters
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
    }
}
