//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsgereMektub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string MainLogo { get; set; }
        public string AktLogo { get; set; }
        public string Fb { get; set; }
        public string Twitter { get; set; }
        public string Insta { get; set; }
        public string Youtube { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string WriteLetterSectionPic { get; set; }
    }
}
